# Generated by Django 6.0.1 on 2026-01-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=25, verbose_name='Apellido')),
                ('correo', models.EmailField(max_length=60, unique=True, verbose_name='Correo')),
                ('edad', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=25)),
                ('marca', models.CharField(max_length=25)),
                ('procesador', models.CharField(max_length=25)),
                ('rom', models.IntegerField()),
                ('ram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buetooth', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('camera', models.BooleanField()),
                ('telefono', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='componente', to='empleado.telefono')),
            ],
        ),
    ]
